### PR TITLE
Adding DeletePortfolio

### PR DESCRIPTION
**Pull request by Abdulrahman123109**
Adding DeletePortfolio

### CODE REVIEW

**Review by robinasaki — CHANGES_REQUESTED** [review]
Please pull from main first, solve conflicts and then push. This commit has too many lines missing.

**Review by JPalubis — CHANGES_REQUESTED** [review]
- Too many import statements removed from Portfolio.java
- Everything else was made cleaner and implemented nicely

**Review by robinasaki — APPROVED** [review]
Good job

**Review by JPalubis — APPROVED** [review]
- Successful changes made to comments I made previously

**Pull request merged**
